// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './brittany-signature-script.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Brittany Signature Script',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Brittany Signature Script'; src: url(${fontUrl}); }`,
  unitsPerEm: 1000,
  ascender: 950,
  descender: -400,
  glyphData,
} as const;

export default bundle;
